<<<<<<< HEAD
DEBUG 2021-03-11 17:04:24.816 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-03-11 17:04:24.817 UTC: 	 Running on: Linux lxplus784.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-03-11 17:04:24.817 UTC: 	 Executing command: 'submit'
DEBUG 2021-03-11 17:04:24.818 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/srosenzw/.crab3
INFO 2021-03-11 17:04:24.842 UTC: 	 Will use CRAB configuration file crabConfig.py
DEBUG 2021-03-11 17:04:24.842 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-03-11 17:04:24.872 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2021-03-11 17:04:24.897 UTC: 	 Working area '/afs/cern.ch/user/s/srosenzw/sixb/CMSSW_10_2_22/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl6_nano_100k/crab_srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl6_nano_100k' already exists 
Please change the requestName in the config file
ERROR 2021-03-11 17:04:24.897 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/s/srosenzw/sixb/CMSSW_10_2_22/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl6_nano_100k/crab_srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl6_nano_100k' already exists 
Please change the requestName in the config file
INFO 2021-03-11 17:04:24.902 UTC: 	 Log file is /afs/cern.ch/user/s/srosenzw/sixb/CMSSW_10_2_22/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/crab.log
=======
DEBUG 2021-07-12 19:32:20.923 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-12 19:32:20.923 UTC: 	 Running on: Linux cmslpc101.fnal.gov 3.10.0-1160.31.1.el7.x86_64 #1 SMP Tue Jun 15 10:20:52 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-07-12 19:32:20.923 UTC: 	 Executing command: 'submit'
DEBUG 2021-07-12 19:32:20.923 UTC: 	 Found CRAB cache file /uscms/home/srosenzw/.crab3
INFO 2021-07-12 19:32:20.925 UTC: 	 Will use CRAB configuration file crabConfig.py
DEBUG 2021-07-12 19:32:20.925 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-07-12 19:32:20.932 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2021-07-12 19:32:20.932 UTC: 	 Working area '/uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_10M/crab_srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_10M' already exists 
Please change the requestName in the config file
ERROR 2021-07-12 19:32:20.932 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_10M/crab_srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_10M' already exists 
Please change the requestName in the config file
INFO 2021-07-12 19:32:20.935 UTC: 	 Log file is /uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/crab.log
DEBUG 2021-07-12 19:46:12.074 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-12 19:46:12.074 UTC: 	 Running on: Linux cmslpc101.fnal.gov 3.10.0-1160.31.1.el7.x86_64 #1 SMP Tue Jun 15 10:20:52 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-07-12 19:46:12.074 UTC: 	 Executing command: 'submit'
DEBUG 2021-07-12 19:46:12.074 UTC: 	 Found CRAB cache file /uscms/home/srosenzw/.crab3
INFO 2021-07-12 19:46:12.076 UTC: 	 Will use CRAB configuration file crabConfig.py
DEBUG 2021-07-12 19:46:12.076 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-07-12 19:46:12.078 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2021-07-12 19:46:12.078 UTC: 	 Working area '/uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_10M/crab_srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_10M' already exists 
Please change the requestName in the config file
ERROR 2021-07-12 19:46:12.078 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_10M/crab_srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_10M' already exists 
Please change the requestName in the config file
INFO 2021-07-12 19:46:12.081 UTC: 	 Log file is /uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/crab.log
DEBUG 2021-07-12 20:40:44.027 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-12 20:40:44.027 UTC: 	 Running on: Linux cmslpc101.fnal.gov 3.10.0-1160.31.1.el7.x86_64 #1 SMP Tue Jun 15 10:20:52 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-07-12 20:40:44.027 UTC: 	 Executing command: 'submit'
DEBUG 2021-07-12 20:40:44.028 UTC: 	 Found CRAB cache file /uscms/home/srosenzw/.crab3
INFO 2021-07-12 20:40:44.040 UTC: 	 Will use CRAB configuration file crabConfig.py
DEBUG 2021-07-12 20:40:44.040 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-07-12 20:40:44.042 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2021-07-12 20:40:44.043 UTC: 	 Working area '/uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_10M/crab_srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_10M' already exists 
Please change the requestName in the config file
ERROR 2021-07-12 20:40:44.043 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_10M/crab_srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_10M' already exists 
Please change the requestName in the config file
INFO 2021-07-12 20:40:44.046 UTC: 	 Log file is /uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/crab.log
DEBUG 2021-07-19 19:41:47.422 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-19 19:41:47.422 UTC: 	 Running on: Linux cmslpc112.fnal.gov 3.10.0-1160.31.1.el7.x86_64 #1 SMP Tue Jun 15 10:20:52 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-07-19 19:41:47.422 UTC: 	 Executing command: 'submit'
DEBUG 2021-07-19 19:41:47.422 UTC: 	 Found CRAB cache file /uscms/home/srosenzw/.crab3
INFO 2021-07-19 19:41:47.433 UTC: 	 Will use CRAB configuration file crabConfig.py
DEBUG 2021-07-19 19:41:47.433 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-07-19 19:41:47.455 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2021-07-19 19:41:47.456 UTC: 	 Working area '/uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_5M_v3/crab_srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_5M_v3' already exists 
Please change the requestName in the config file
ERROR 2021-07-19 19:41:47.456 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_5M_v3/crab_srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_5M_v3' already exists 
Please change the requestName in the config file
INFO 2021-07-19 19:41:47.457 UTC: 	 Log file is /uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/crab.log
DEBUG 2021-07-20 17:17:50.773 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-20 17:17:50.773 UTC: 	 Running on: Linux cmslpc116.fnal.gov 3.10.0-1160.31.1.el7.x86_64 #1 SMP Tue Jun 15 10:20:52 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-07-20 17:17:50.773 UTC: 	 Executing command: 'submit'
DEBUG 2021-07-20 17:17:50.774 UTC: 	 Found CRAB cache file /uscms/home/srosenzw/.crab3
INFO 2021-07-20 17:17:50.788 UTC: 	 Will use CRAB configuration file crabConfig.py
DEBUG 2021-07-20 17:17:50.788 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-07-20 17:17:50.804 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2021-07-20 17:17:50.805 UTC: 	 Working area '/uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_5M_v4/crab_srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_5M_v4' already exists 
Please change the requestName in the config file
ERROR 2021-07-20 17:17:50.806 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_5M_v4/crab_srosenzw_NMSSM_XYH_YToHH_6b_MX_700_MY_400_sl7_nano_5M_v4' already exists 
Please change the requestName in the config file
INFO 2021-07-20 17:17:50.808 UTC: 	 Log file is /uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_2_18/src/sixB/FullSim/Era_2018/NMSSM_XYH_YToHH_6b_MX_700_MY_400/crab.log
>>>>>>> 76c4c43df0dab6994a89dc5f4c504006c20990ae
