DEBUG 2022-04-04 21:03:44.608 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-04-04 21:03:44.608 UTC: 	 Running on: Linux cmslpc123.fnal.gov 3.10.0-1160.53.1.el7.x86_64 #1 SMP Tue Jan 11 08:25:52 CST 2022 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2022-04-04 21:03:44.609 UTC: 	 Executing command: 'status'
DEBUG 2022-04-04 21:03:44.609 UTC: 	 Found CRAB cache file /uscms/home/srosenzw/.crab3
ERROR 2022-04-04 21:03:44.614 UTC: 	 Error: srosenzw_NMSSM_XYH_YToHH_6b_MX_500_MY_300_sl7_nano_100k/crab_srosenzw_NMSSM_XYH_YToHH_6b_MX_500_MY_300_sl7_nano_100k is not a valid CRAB project directory.
ERROR 2022-04-04 21:03:44.614 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 162, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 147, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: srosenzw_NMSSM_XYH_YToHH_6b_MX_500_MY_300_sl7_nano_100k/crab_srosenzw_NMSSM_XYH_YToHH_6b_MX_500_MY_300_sl7_nano_100k is not a valid CRAB project directory.
INFO 2022-04-04 21:03:44.617 UTC: 	 Log file is /uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_6_19_patch2/src/sixB/analysis/sixBanalysis/crab.log
